### ISSUE TITLE
[BUG] Estimert tid-felt er veldig uintuitvt

### ISSUE THREAD

**Issue by kalleruud** [Releets/pluginregistrationapp#15]
Når jeg prøver å legger inn navn + tidspunkt jeg er ferdig...

<img width="387" alt="Screenshot 2024-09-01 at 20 13 36" src="https://github.com/user-attachments/assets/20e9d9a4-f89a-4c5a-94a6-1a1b0a26b3e7">

... får jeg lagt til tiden jeg legger inn som antall timer

<img width="267" alt="Screenshot 2024-09-01 at 20 14 11" src="https://github.com/user-attachments/assets/5f96872c-0c40-4a8e-a2d2-64d8d9de6701">

**Comment by ramikw** [comment]
😁

**Comment by Releets** [comment]
I blame QA
