### ISSUE TITLE
Esitmated completion should be from the moment a user is first in line

### ISSUE THREAD

**Issue by kalleruud** [Releets/pluginregistrationapp#22]
If a user goes into the queue estimating 1 hour behind someone est. 2 hours, the user in the queue will be removed before its their turn

<img width="549" alt="Screenshot 2024-09-01 at 23 05 13" src="https://github.com/user-attachments/assets/50452d73-3b7c-4bb9-b604-4b99398c2f06">

**Comment by Releets** [comment]
Showing startime and estimates for people not at the front of the queue doesnt make much sense.
The time should be set when you overtake the queue, and the estimate should be calculated based on your actual start-time
